# Generated by Django 3.1.6 on 2021-02-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('write_time', models.DateTimeField()),
                ('read_count', models.IntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('write_time', models.DateTimeField()),
                ('read_count', models.IntegerField()),
                ('board_replied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.board')),
            ],
        ),
    ]
